[agent]
  interval = "10s"
  flush_interval = "2s"
  omit_hostname = true

[[inputs.cisco_telemetry_mdt]]
  transport = "grpc"
  service_address = ":57500"

[[outputs.file]]
  files = ["/sidecar/decoded.json"]
  data_format = "json"
  json_timestamp_units = "1s"
